name: PyInstaller Windows

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with PyInstaller
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          path: .
